### ISSUE TITLE
When Wine application is installed, VTFs aren't read correctly?

### ISSUE THREAD

**Issue by Xylemon** [panzi/KIO-VTF-Thumb-Creator#1]
This one is weird, it seems that my installation of VTFEdit under Wine screws with VTF's working with Dolphin or Gwenview. I have not tried it on a clean system before so I can not confirm but I noticed that the file format is now known to the system as: 

x-wine-extension-vtf

Any idea how to fix this?

**Comment by panzi** [comment]
Well, Windows Programs can register mime types via the registry. I guess wine bridges this into the Linux mime type system. So this isn't strictly a bug of the kio plugin. Anyway, I guess you should be able to fix this by deleting the x-wine-extension-vtf file association. I'm not sure what you have to delete exactly to do this, but I guess running `find ~/.local/share/mime/ -iname '*x-wine-extension-vtf*' -exec rm {} \;` and then `update-mime-database ~/.local/share/mime/` and then re-install the kio plugin should do the trick. This is from memory and can be totally wrong, though. Maybe you have to do something with `~/.local/share/applications` instead?

**Comment by Xylemon** [comment]
I've done this twice so far with a reboot and it seems to keep reverting it back to "x-wine-extension-vtf". I even uninstalled VTFEdit, but no luck.

**Comment by panzi** [comment]
Maybe you need to delete the file associations in the Windows registry. Search for appropriate sections in `~/.wine/*.reg` (probably only `~/.wine/user.reg`) and delete them (search for `FileOpenAssociations`). This is a total guess, so don't blame me if it ruins anything. :)
